sudo: false

language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build
  - mkdir html
  - cp -r dist index.html html/

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    tags: true
